//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailMarketingHubPOC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADSingleValue
    {
        public int ObjectID { get; set; }
        public Nullable<bool> iscriticalsystemobject { get; set; }
        public Nullable<bool> mapirecipient { get; set; }
        public Nullable<System.Guid> objectguid { get; set; }
        public string objectsid { get; set; }
        public byte[] thumbnailphoto { get; set; }
        public Nullable<System.DateTime> whenchanged { get; set; }
        public Nullable<System.DateTime> whencreated { get; set; }
        public Nullable<int> admincount { get; set; }
        public Nullable<int> badpwdcount { get; set; }
        public Nullable<int> countrycode { get; set; }
        public Nullable<int> deleteditemflags { get; set; }
        public Nullable<int> grouptype { get; set; }
        public Nullable<int> instancetype { get; set; }
        public Nullable<int> internetencoding { get; set; }
        public Nullable<int> logoncount { get; set; }
        public Nullable<int> primarygroupid { get; set; }
        public Nullable<int> samaccounttype { get; set; }
        public Nullable<int> systemflags { get; set; }
        public Nullable<int> useraccountcontrol { get; set; }
        public Nullable<long> accountexpires { get; set; }
        public Nullable<long> badpasswordtime { get; set; }
        public Nullable<long> lastlogoff { get; set; }
        public Nullable<long> lastlogon { get; set; }
        public Nullable<long> lastlogontimestamp { get; set; }
        public Nullable<long> lockouttime { get; set; }
        public Nullable<long> pwdlastset { get; set; }
        public Nullable<long> usnchanged { get; set; }
        public Nullable<long> usncreated { get; set; }
        public string adspath { get; set; }
        public string altrecipient { get; set; }
        public string assistant { get; set; }
        public string autoreplymessage { get; set; }
        public string cn { get; set; }
        public string co { get; set; }
        public string comment { get; set; }
        public string company { get; set; }
        public string department { get; set; }
        public string description { get; set; }
        public string displayname { get; set; }
        public string displaynameprintable { get; set; }
        public string distinguishedname { get; set; }
        public string facsimiletelephonenumber { get; set; }
        public string folderpathname { get; set; }
        public string givenname { get; set; }
        public string homedirectory { get; set; }
        public string homedrive { get; set; }
        public string homemdb { get; set; }
        public string homemta { get; set; }
        public string homephone { get; set; }
        public string info { get; set; }
        public string initials { get; set; }
        public string ipphone { get; set; }
        public string l { get; set; }
        public string mail { get; set; }
        public string mailnickname { get; set; }
        public string managedby { get; set; }
        public string manager { get; set; }
        public string mobile { get; set; }
        public string msexchhomeservername { get; set; }
        public string name { get; set; }
        public string objectcategory { get; set; }
        public string otherhomephone { get; set; }
        public string otherpager { get; set; }
        public string othertelephone { get; set; }
        public string pager { get; set; }
        public string physicaldeliveryofficename { get; set; }
        public string postalcode { get; set; }
        public string samaccountname { get; set; }
        public string sn { get; set; }
        public string st { get; set; }
        public string streetaddress { get; set; }
        public string targetaddress { get; set; }
        public string telephoneassistant { get; set; }
        public string telephonenumber { get; set; }
        public string textencodedoraddress { get; set; }
        public string title { get; set; }
        public string unauthorig { get; set; }
        public string unauthorigbl { get; set; }
        public string userprincipalname { get; set; }
        public string wwwhomepage { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
